config/routes.rb
Rails.application.routes.draw do
  resources :links, only: [:show, :new, :create]

  root to: redirect('/links/new')

end

app/models/link.rb
class Link < ActiveRecord::Base
	validates :link, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :params_permit, only: [:new] 
	

  def index
  	@links = Link.all	
  end	

  def new
  	@link = Link.new
  end

  def create
  	@link = Link.new link_params
  	@link.short_url = root_url + rand(36**4).to_s(36)
  	if @link.save
  		flash[:link_id] = @link.id
  		redirect_to new_link_path
  	else
  		render "new"
  	end
  end

  def show
  	@link = Link.find(params[:id])
  	redirect_to @link.link
  end


  private

  def link_params
    params.require(:link).permit(:link, :short_url)
  end

  def params_permit
    params.permit(:show_all)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Shrinky</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:link_id].present? %>
	<p class="shortlink" >
		The Shrinky Link is available <%= link_to 'here', link_path(flash[:link_id]) %>. (Right click and copy link to share it.) </p>
		<% end %>

		<%= yield %>

	</body>
	</html>

app/views/links/new.html.erb
<h1>Shrinky Link</h1>
<p>Get a shortlink by Shrinky Link from a long URL</p>

<%= @link.link %>
<h3>Add a new URL</h3>
<%= form_for @link do |f| %>

  <p>
    <%= f.label :link, "Your URL:" %>
    <%= f.text_field :link %>
  </p>

  <% if @link.errors[:link].any? %>
    <p class='error-messages'>
      The given url <%= @link.errors[:link].to_sentence %>.
    </p>
  <% end %>

  <p class='buttons'>
    <%= f.submit "Shorten my URL" %>
  </p>

<% end %>

<p>See past links Shrinkied Before! <%= link_to 'Shrinkied Links', new_link_path(show_all: "true") %></p>
    <% if params[:show_all] %>
      <% Link.all.each do |the_url| %>
        <div>
          <%= the_url.link %> + <%= the_url.short_url %> 
        </div>
      <% end %>
    <% end %>